{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "toc_visible": true,
      "authorship_tag": "ABX9TyPTuQa5nUrkTNPgNOtlKipD",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ooy4ke/test/blob/main/discord.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "\n",
        "#discord.pyについて\n",
        "\n",
        "\n",
        "##discord.pyとは\n",
        "discord.pyは、PythonでDiscord Botを作る際にもっともよく使われているAPIラッパーです。GitHubでソースコードが公開されています。discord.pyには、discord.ext.commandsという拡張フレームワークがあります。今回、 discord.ext.commandsフレームワークについて学びながら、簡単なbotの作り方を書いていきます。 <br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "##準備\n",
        " discord.pyを動かすには、「Python3.5.3以上」、また、「Botアカウント」「トークン」を 事前に用意する必要があるため、その説明を書いていきます。また、VS Codeもインストールするためその説明を書いていきます。<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "##Python\n",
        "https://www.python.org/  にまずアクセスします。  \n",
        "その後下の写真の➀にカーソルを持っていき、②をクリックしてダウンロードします。<br>\n",
        "![pythonダウンロード](https://drive.google.com/uc?export=view&id=1ByTyQUYcDoD8DhTvMFDNuMtuKzfhRBtb)<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "インストールしたものを開いた後、下の写真の➀にチェックを入れ、②でインストールします。<br>\n",
        "![pythonインストール](https://drive.google.com/uc?export=view&id=1CREYTOOQOHOmJyGRg67-97AgC8X8_IU8)\n",
        "<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "##Visual Studio Code\n",
        "\n",
        "###VS Codeのインストール\n",
        "\n",
        "https://code.visualstudio.com/ にまずアクセスします。  \n",
        "その後、windows用ダウンロードからダウンロードします。<br>\n",
        "![vscodeダウンロード](https://drive.google.com/uc?export=view&id=11O1Vk6XHSfuEC1iU05ASviTn_CGgoCx2)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "インストールしたものを開いて、同意するにチェックを入れて次へを押し、設定はデフォルトでインストールします。\n",
        "![vscodeインストール](https://drive.google.com/uc?export=view&id=1gLHtUfLaFrybYCH_ROo3OOgifpqD8oBw)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "➀のところにあるVS CodeのViewメニューから、②のCommand Pallete...を選択し、出てくる入力フィールドに  `Configure Display Language`と入力します。  \n",
        "\n",
        "\n",
        "\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=1dg_jbklyb1nHgLqQLKol6acDwCuYfcpX)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "表示される一覧から、Install Additional Languages をクリックします。  \n",
        "一覧から日本語を選択し、Install ボタンをクリックしてインストールします。  \n",
        "これで日本語設定になります。<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "###Python開発環境をインストール\n",
        "VS Codeを起動したら、Python Extension for Visual Studio Code をインストールします。Python Extension for Visual Studio Code はVS CodeでPythonを開発するための機能拡張です。<br><br>\n",
        "\n",
        "\n",
        "\n",
        "まず、VS Codeの ファイルメニューの ユーザ設定 → 拡張機能 を選択して、VS Code拡張機能の管理画面を表示します。\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=1vdpi1fhvXjUkdyXq64IIYtTdlii-lzK3)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "画面左上の Marketplaceで拡張機能を検索するに、ms-pythonと入力し、検索した一覧で Python をクリック、インストールを押してインストールします。\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=1TSptXEB6NLrcWMiatEN2U-TUoX1g_RB4)\n",
        "<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "##Discord Botアカウントとトークン\n",
        "Discord Botをつくるには、自分のアカウントとは別に、Bot用アカウントを用意する必要があります。Bot用アカウントの作り方について手順を記します。<br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "まず自分のdiscordのアカウントにログインしてください。そのアカウントでBotを招待する用の自分のサーバーを一つ用意してください。<br><br>\n",
        "\n",
        "\n",
        "それが出来たらhttps://discord.com/developers/applications にアクセスし、「Create New App」をクリックします。\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=1tktBxhC-nwjt6K-x7kF_R7RHBFPXc1v7)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "その後、名前を付けて「create」を押すとアプリケーションが作れます。<br><br>\n",
        "\n",
        "\n",
        "右のメニューから「Bot」を選択し、「Reset Token」を押すとトークンが出てきます。このトークンは必ず保存して、ほかの人にはばれないようにしてください。  \n",
        "\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=1rQ4wM4xTt2en0RORGnkTTzQdgSNr6kb6)\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "（ネットの記事には「Bot」を選択した後、「Add Bot」を押し、「Yes, do it.」をクリックするとトークンが出てくると書いてあったので上のような画面にならない人はそのやり方でしてください。）<br><br>\n",
        "\n",
        "\n",
        "\n",
        "「OAuth2」を選択、「URL Generator」を押して、「SCOPES」の「bot」を選択します。\n",
        "![vscode日本語設定](https://drive.google.com/uc?export=view&id=177tVHPNyiczx2VC07gJiNNKJlRuHiRUI)\n",
        "下にスクロールしていくと「GENERATED URL」があるので「copy」を押してURLをコピーします。  \n",
        "新しくブラウザを開き、そのURLを貼り付けます。  \n",
        "そして出てきた画面でbotを追加するサーバーを選び、決定するとbotがサーバーに追加されます。<br><br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "##discord.pyを動かすには\n",
        "ここからは簡単なdiscordのbotの作り方について書いていきます。本を参考にして行っていますが、本の通りに行ってもうまくいかない部分が多々あったので、自分の対処法も書いていきます。<br><br><br>\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "1. CLIを開く  \n",
        "今回、ライブラリーのインストールやプログラムの実行は、OS上のCLIから行います。Linuxならターミナル、Windowsならコマンドラインプロンプトを開いてください。Windowsでコマンドラインプロンプトを開くには、windowsメニューを開いてcmdと入力し、エンターキーを押します。\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "\n",
        "2. discord.pyをインストールする  \n",
        "Bot開発を支援する イブラリー「discord.py」をインストールします。\n",
        "'''\n",
        "$ python 3 -m pip install -U discord. py < Enter > ← Linux の 場合 $ py -3 -m pip install -U discord. py < Enter > ← Windows の 場合\n",
        "'''\n",
        "\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "a9v-BQ6V6-cq"
      }
    }
  ]
}